# f) Ngonye Falls Power and Energy Periods
Produces summary, agrregated results from the daily power and energy modelling.


## Inputs

| Data                       | Source                                        | Description                                 |
|----------------------------|-----------------------------------------------|---------------------------------------------|
| [Model Name]_pe_daily.csv | Notebook: e_power_energy | Daily power output  |


## Outputs
| File                           | Description                                 |
|--------------------------------|---------------------------------------------|
|    [Model Name]_pe_daily.csv ||
|    [Model Name]_pe_monthly.csv||
|    [Model Name]_pe_yearly.csv||
|    [Model Name]_pe_percentiles.csv||
|    [Model Name]_pe_monthly_day.csv||
|    [Model Name]_pe_daily_slim.csv||
|    [Model Name]_pe_weekly.csv||
|    [Model Name]_pe_weekly_slim.csv||
|    [Model Name]_pe_calmonthly.csv||
|    [Model Name]_pe_fdc.csv||
|    [Model Name]_pe_power_exceed.csv||
|    models.csv| |

## Libraries and Setup

In [404]:
import numpy as np
import pandas as pd
from scipy import interpolate
import math
import statsmodels.tsa.stattools as statools

## Parameters

In [405]:
year = ""

In [406]:
input_data='./input_data/'
output_data='./output_data/'

if year != '':
    output_data += year + '/'

input_data, output_data

('./input_data/', './output_data/')

Set the model name below. This is used to lookup model parameters from the models list file.

- Base Case: Base Case
- MW162: Capacity reduced to 162MW
- Headpond50cm: Headpond level increased by 50cm
- EWRAllCs: All river reaches at a C rather than B environmental assurance level
- Extend Head: Minimum head reduce from 10m to 9m
- Tailwater Rise 50cm: Tailwater curve raised by 50cm
- Tailwater Fall 50cm: Tailwater curve dropped by 50cm

In [407]:
model_name='Base Case Tender'
dryrun=False #Dont write output files
output_separate_years=True

In [408]:
if year != '':
    model_file=input_data + year + "/models.csv"
else:
    model_file=input_data + "models.csv"

models=pd.read_csv(model_file).set_index('ModelName')
model=models.loc[model_name]

out_prefix=model['OutputPrefix']#'base'
if out_prefix!='base':
    out_prefix="/scenarios/" + out_prefix

category_set_name=model['EWRCatSet']#'Recommendation 1'
headpond_lift=model['HeadpondLift']#0
tailwater_lift=model['TailwaterLift']#0

plant_capacity=model['Capacity'] #Base 180MW nominal capacity
# units=4 #Design no of units
units_avialable=model['UnitsAvailable'] #Available no of units

max_flow_unit=model['MaximumFlowUnit'] #275
canal_capacity=max_flow_unit*4 #canal capacity 1100 cumec 
min_flow_unit=model['MinimumFlowUnit'] #50cumec minimum flow for a turbine

head_minimum=model['MinimumHead'] #minimum head 10m
head_maximum=model['MaximumHead'] #maximum head 25.4m
rated_turbine_capacity=model['RatedTurbineCapacity'] #49.1MW
max_generator_output=model['MaxGeneratorOutput'] #48.2MW

optimise_turbines = model['OptimiseTurbines']

use_sino_hillchart = model['SinoHillchart']
use_sino_headlosses = model['SinoHeadlosses']

#rated_power_unit=rated_flow_unit*model['RatedHead']*model['RatedTurbineEfficiency']*model['RatedGeneratorEfficiency']*9.81/1000

model

OutputPrefix                                               base_tender
Description             Base Case as provided to EPC Tender candidates
EWRCatSet                                             Recommendation 1
TailwaterLift                                                      0.0
HeadpondLift                                                       0.0
Capacity                                                           180
MinimumHead                                                       10.0
MaximumHead                                                       25.4
MaxHeadShutdown                                                    0.0
MinimumFlowUnit                                                   50.0
MaximumFlowUnit                                                  275.0
UnitsAvailable                                                       4
RatedDischarge                                                   250.0
RatedTurbineCapacity                                              49.1
MaxGeneratorOutput                                                48.2
OptimiseTurbines                                                     0
SinoHillchart                                                        0
SinoHeadlosses                                                       0
Mean                                                     828370.524152
P95                                                      715491.078684
P90                                                      756255.037323
P75                                                      791563.774163
P50                                                      831479.739441
P25                                                      865049.148011
P10                                                      921297.666883
P5                                                       944522.904684
StDev                                                     80703.703173
CoefVar                                                       0.097425
Max                                                     1005722.657187
Min                                                      487344.503302
CapFactor                                                     0.525349
CalYearMean                                              828469.058294
CalYearStDev                                              78872.987434
CalYearCoefVar                                                0.095203
AutoCorrel                                                         NaN
Power_max                                                        192.8
CapFactor_Power_max                                            0.49053
Power_Turbine1_max                                           61.532301
P95FirmPower                                                 26.897955
P90FirmPower                                                  30.64712
Name: Base Case Tender, dtype: object

## Load Daily Data

Load the daily time series which includes the exceedance values used for calculating daily EWRs.

In [409]:
daily_file = output_data + out_prefix + '_pe_daily.csv'
daily=pd.read_csv(daily_file) #ngonye_daily_WC1_1_base_pe
daily=daily.set_index(pd.to_datetime(daily['Date'],format="%Y-%m-%d"))
daily=daily.drop('Date',axis=1)
daily_file, daily.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 33968 entries, 1924-10-01 to 2017-09-30
Data columns (total 86 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   LaggedDate                  33968 non-null  object
 1   VicFalls                    33968 non-null  float64
 2   Conversion                  33968 non-null  float64
 3   Flow                        33968 non-null  float64
 4   Exceedance                  33968 non-null  float64
 5   Year                        33968 non-null  int64
 6   Month                       33968 non-null  int64
 7   Day                         33968 non-null  int64
 8   MonthId                     33968 non-null  float64
 9   WaterYear                   33968 non-null  int64
 10  WaterMonth                  33968 non-null  int64
 11  WaterDay                    33968 non-null  int64
 12  WaterWeek                   33968 non-null  int64
 13  Volume                      33968 non-null  float64
 14  Flow_difference             33968 non-null  float64
 15  Flow_difference_pct         33968 non-null  float64
 16  EWRRefExceedance            33968 non-null  float64
 17  EWRBandNo                   33968 non-null  int64
 18  EWRBandLabel                33968 non-null  object
 19  EWRChannelA                 33968 non-null  int64
 20  EWRChannelC                 33968 non-null  int64
 21  EWRChannelD                 33968 non-null  int64
 22  EWRChannelE                 33968 non-null  int64
 23  EWRChannelFG                33968 non-null  int64
 24  EWRTotal                    33968 non-null  float64
 25  EWRProportion               33968 non-null  float64
 26  FlowAvailableForGeneration  33968 non-null  float64
 27  FlowCanal                   33968 non-null  float64
 28  LowFlowShutoff              10 non-null     float64
 29  Turbines                    33968 non-null  int64
 30  FlowTurbine1                33968 non-null  float64
 31  FlowTurbine2                33968 non-null  float64
 32  FlowTurbine3                33968 non-null  float64
 33  FlowTurbine4                33968 non-null  float64
 34  FlowSpill                   33968 non-null  float64
 35  SpillChannelA               33968 non-null  float64
 36  SpillChannelC               33968 non-null  float64
 37  SpillChannelD               33968 non-null  float64
 38  SpillChannelE               33968 non-null  float64
 39  SpillChannelFG              33968 non-null  float64
 40  FlowChannelA                33968 non-null  float64
 41  FlowChannelC                33968 non-null  float64
 42  FlowChannelD                33968 non-null  float64
 43  FlowChannelE                33968 non-null  float64
 44  FlowChannelFG               33968 non-null  float64
 45  FlowLeftChannel             33968 non-null  float64
 46  LevelHeadpond               33968 non-null  float64
 47  LevelTailwater              33968 non-null  float64
 48  HeadGross                   33968 non-null  float64
 49  HeadlossLeftChannel         33968 non-null  float64
 50  HeadlossCanal               33968 non-null  float64
 51  LevelForebay                33968 non-null  float64
 52  HeadlossTurbine1            33968 non-null  float64
 53  HeadlossTurbine2            33968 non-null  float64
 54  HeadlossTurbine3            33968 non-null  float64
 55  HeadlossTurbine4            33968 non-null  float64
 56  HeadTurbine1                33968 non-null  float64
 57  HeadTurbine2                33968 non-null  float64
 58  HeadTurbine3                33968 non-null  float64
 59  HeadTurbine4                33968 non-null  float64
 60  LowHeadShutoff              397 non-null    float64
 61  EffTurbine1                 33968 non-null  float64
 62  EffTurbine2                 33968 non-null  float64
 63  EffTurbine3                 33968 non-null  float64
 64  EffTurbine4                 33968 non-null  float64
 65  PowerTurbine1               33968 non-null  float64
 66  PowerTurbine2               33968 non-null  float64
 67  PowerTurbine3               33968 non-null  float64
 68  PowerTurbine4               33968 non-null  float64
 69  LoadFactorTurbine1          33968 non-null  float64
 70  LoadFactorTurbine2          33968 non-null  float64
 71  LoadFactorTurbine3          33968 non-null  float64
 72  LoadFactorTurbine4          33968 non-null  float64
 73  EffGen1                     33968 non-null  float64
 74  EffGen2                     33968 non-null  float64
 75  EffGen3                     33968 non-null  float64
 76  EffGen4                     33968 non-null  float64
 77  PowerGenerator1             33968 non-null  float64
 78  PowerGenerator2             33968 non-null  float64
 79  PowerGenerator3             33968 non-null  float64
 80  PowerGenerator4             33968 non-null  float64
 81  Power                       33968 non-null  float64
 82  Energy                      33968 non-null  float64
 83  PerfMwPerCumec              33968 non-null  float64
 84  PerfMWhPerm3                33958 non-null  float64
 85  ExceedanceRnd               33968 non-null  float64
dtypes: float64(70), int64(14), object(2)
memory usage: 22.5+ MB

('./output_data//scenarios/base_tender_pe_daily.csv', None)

In [410]:
monthly=daily.groupby("MonthId").mean(numeric_only=True).drop(['Day','EWRBandNo','EWRRefExceedance','Energy'],axis=1)

if 'VicFalls' in monthly.columns:
    monthly=monthly.drop(['VicFalls','Conversion','Volume','WaterDay','WaterWeek','Volume'],axis=1)

monthly=monthly.join(daily.groupby("MonthId").agg(    
   Power_max=('Power', 'max'),
   Power_min=('Power', 'min'),   
   Turbines_max=('Turbines', 'max'),    
   Turbines_min=('Turbines', 'min'),   
   Energy=('Energy', 'sum'),
   FlowAvailableForGeneration_min=('FlowAvailableForGeneration','min')
))
monthly['Days']=monthly.apply(lambda x: pd.Period(year=x['Year'],month=x['Month'],freq='D').days_in_month,axis=1)
monthly['CapFactor']=monthly['Energy']/(plant_capacity*24*monthly['Days'])

monthly

,Flow,Exceedance,Year,Month,WaterYear,WaterMonth,Flow_difference,Flow_difference_pct,EWRChannelA,EWRChannelC,...,PerfMWhPerm3,ExceedanceRnd,Power_max,Power_min,Turbines_max,Turbines_min,Energy,FlowAvailableForGeneration_min,Days,CapFactor
MonthId,,,,,,,,,,,,,,,,,,,,,
1924.10,116.382415,0.998677,1924.0,10.0,1924.0,1.0,0.537958,0.020360,28.193548,4.322581,...,0.000054,1.000000,15.061287,0.000000,1,0,6608.486364,14.407480,31,0.049347
1924.11,153.980092,0.991767,1924.0,11.0,1924.0,2.0,2.291751,0.014462,23.000000,4.000000,...,0.000059,0.991333,31.111556,15.916712,1,1,15962.581410,78.245150,30,0.123168
1924.12,275.677198,0.831290,1924.0,12.0,1924.0,3.0,9.228880,0.030062,26.000000,4.000000,...,0.000060,0.831452,81.196678,29.414225,2,1,34801.255362,133.895237,31,0.259866
1925.01,692.738673,0.458161,1925.0,1.0,1924.0,4.0,41.218566,0.052636,37.129032,5.677419,...,0.000055,0.458710,190.815438,73.147468,4,2,85565.341291,344.857772,31,0.638929
1925.02,1193.678452,0.278214,1925.0,2.0,1924.0,5.0,24.865166,0.020264,49.000000,8.000000,...,0.000050,0.277679,190.055647,174.684889,4,4,122454.499911,945.711819,28,1.012355
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017.05,2195.626922,0.156581,2017.0,5.0,2016.0,8.0,38.011322,0.017650,55.000000,13.000000,...,0.000041,0.156935,179.054422,144.380346,4,4,119733.171688,1362.344662,31,0.894065
2017.06,1118.647129,0.312300,2017.0,6.0,2016.0,9.0,32.020074,0.029916,53.000000,12.000000,...,0.000051,0.312000,191.126606,96.040580,4,2,111785.596925,467.742437,30,0.862543
2017.07,482.692384,0.575419,2017.0,7.0,2016.0,10.0,9.727121,0.019150,50.000000,10.000000,...,0.000058,0.575323,95.559156,42.559931,2,1,45676.276513,195.711656,31,0.341071
2017.08,318.145603,0.759677,2017.0,8.0,2016.0,11.0,3.795014,0.011987,39.000000,7.000000,...,0.000059,0.760000,48.200000,32.474413,1,1,32058.577916,149.066213,31,0.239386
2017.09,223.955095,0.918100,2017.0,9.0,2016.0,12.0,2.135103,0.009348,34.000000,6.000000,...,0.000061,0.917833,37.458283,23.512430,1,1,20872.284992,109.013130,30,0.161052

In [411]:
yearly=daily.groupby("WaterYear").agg(
   Flow_max=('Flow', 'max'),
   Flow_min=('Flow', 'min'), 
   EWRProportion_max=('EWRProportion', 'max'),
   EWRProportion_min=('EWRProportion', 'min'),
   HeadTurbine1_max=('HeadTurbine1', 'max'),
   HeadTurbine1_min=('HeadTurbine1', 'min'),   
   PowerTurbine1_max=('PowerTurbine1', 'max'),    
   LevelTailwater_max=('LevelTailwater', 'max'),
   LevelTailwater_min=('LevelTailwater', 'min'),  
   Power_max=('Power', 'max'),
   Power_min=('Power', 'min'),    
   Energy=('Energy', 'sum'),
)
yearly['CapFactor']=yearly['Energy']/(plant_capacity*24*365)

In [412]:
yearly.tail(5)

,Flow_max,Flow_min,EWRProportion_max,EWRProportion_min,HeadTurbine1_max,HeadTurbine1_min,PowerTurbine1_max,LevelTailwater_max,LevelTailwater_min,Power_max,Power_min,Energy,CapFactor
WaterYear,,,,,,,,,,,,,
2012,3614.802471,223.273423,0.508220,0.055826,25.248861,13.195062,61.034111,974.863748,964.539641,192.800000,24.579669,837085.872251,0.530876
2013,3574.946119,195.061590,0.497279,0.056428,25.400000,13.279520,60.147298,974.779291,964.400079,192.334429,20.770617,923035.171898,0.585385
2014,1460.253290,208.780681,0.546606,0.092833,25.354693,18.747311,61.097887,969.356203,964.452684,192.800000,25.581039,879487.967546,0.557768
2015,2975.524395,176.218173,0.496598,0.067347,25.391596,14.604097,61.102207,973.454714,964.400079,192.800000,22.055102,785175.264047,0.497955
2016,3889.991232,156.550907,0.487279,0.047442,25.400000,12.611924,59.987618,975.446886,964.400079,192.582246,19.727459,847550.834251,0.537513

In [413]:
yearly['Prop4Units']=daily[['WaterYear','Turbines']].groupby('WaterYear').agg(lambda x: sum(np.where(x==4,1,0))/365)
yearly['Prop3Units']=daily[['WaterYear','Turbines']].groupby('WaterYear').agg(lambda x: sum(np.where(x==3,1,0))/365)
yearly['Prop2Units']=daily[['WaterYear','Turbines']].groupby('WaterYear').agg(lambda x: sum(np.where(x==2,1,0))/365)
yearly['Prop1Units']=daily[['WaterYear','Turbines']].groupby('WaterYear').agg(lambda x: sum(np.where(x==1,1,0))/365)
yearly['Prop0Units']=daily[['WaterYear','Turbines']].groupby('WaterYear').agg(lambda x: sum(np.where(x==0,1,0))/365)
yearly['Days0Units']=daily[['WaterYear','Turbines']].groupby('WaterYear').agg(lambda x: sum(np.where(x==0,1,0)))

In [414]:
# yearly['PropDays1uPotentialGtRatedPower']=daily[['WaterYear','PotentialPower1u']].where(lambda x: x['PotentialPower1u']>rated_power_unit).groupby('WaterYear').count()
# yearly['PropDays2uPotentialGtRatedPower']=daily[['WaterYear','PotentialPower2u']].where(lambda x: x['PotentialPower2u']>rated_power_unit*2).groupby('WaterYear').count()
# yearly['PropDays3uPotentialGtRatedPower']=daily[['WaterYear','PotentialPower3u']].where(lambda x: x['PotentialPower3u']>rated_power_unit*3).groupby('WaterYear').count()
# yearly['PropDays4uPotentialGtRatedPower']=daily[['WaterYear','PotentialPower4u']].where(lambda x: x['PotentialPower4u']>yearly['Power_max'].max()).groupby('WaterYear').count()

In [415]:
#daily.reset_index()[['Date','WaterYear','PotentialPower1u']].where(lambda x: x['PotentialPower1u']<rated_power_unit).groupby('WaterYear').min()['Date'].apply(lambda x: pd.Timestamp(x).dayofyear)

In [416]:
# yearly['FstDay1uPotentialLessRatedPower']=daily.reset_index()[['Date','WaterYear','PotentialPower1u']].where(lambda x: x['PotentialPower1u']<rated_power_unit).groupby('WaterYear').min()['Date'].apply(lambda x: pd.Timestamp(x).dayofyear)
# yearly['LstDay1uPotentialLessRatedPower']=daily.reset_index()[['Date','WaterYear','PotentialPower1u']].where(lambda x: x['PotentialPower1u']<rated_power_unit).groupby('WaterYear').max()['Date'].apply(lambda x: pd.Timestamp(x).dayofyear)

# yearly['FstDay2uPotentialLessRatedPower']=daily.reset_index()[['Date','WaterYear','PotentialPower2u']].where(lambda x: x['PotentialPower2u']<rated_power_unit*2).groupby('WaterYear').min()['Date'].apply(lambda x: pd.Timestamp(x).dayofyear)
# yearly['LstDay2uPotentialLessRatedPower']=daily.reset_index()[['Date','WaterYear','PotentialPower2u']].where(lambda x: x['PotentialPower2u']<rated_power_unit*2).groupby('WaterYear').max()['Date'].apply(lambda x: pd.Timestamp(x).dayofyear)

# yearly['FstDay3uPotentialLessRatedPower']=daily.reset_index()[['Date','WaterYear','PotentialPower3u']].where(lambda x: x['PotentialPower3u']<rated_power_unit*3).groupby('WaterYear').min()['Date'].apply(lambda x: pd.Timestamp(x).dayofyear)
# yearly['LstDay3uPotentialLessRatedPower']=daily.reset_index()[['Date','WaterYear','PotentialPower3u']].where(lambda x: x['PotentialPower3u']<rated_power_unit*3).groupby('WaterYear').max()['Date'].apply(lambda x: pd.Timestamp(x).dayofyear)

# yearly['FstDay4uPotentialLessRatedPower']=daily.reset_index()[['Date','WaterYear','PotentialPower4u']].where(lambda x: x['PotentialPower4u']<yearly['Power_max'].max()).groupby('WaterYear').min()['Date'].apply(lambda x: pd.Timestamp(x).dayofyear)
# yearly['LstDay4uPotentialLessRatedPower']=daily.reset_index()[['Date','WaterYear','PotentialPower4u']].where(lambda x: x['PotentialPower4u']<yearly['Power_max'].max()).groupby('WaterYear').max()['Date'].apply(lambda x: pd.Timestamp(x).dayofyear)

## Power and energy exceedance

In [417]:
power_exceed=pd.DataFrame(index=np.arange(0,1.05,0.05))
power_exceed.index=power_exceed.index.rename('Exceedance')
power_exceed['Power']=np.percentile(daily['Power'],(1-power_exceed.index)*100)
power_exceed

                 Power
Exceedance
0.00        192.800000
0.05        183.165107
0.10        174.022634
0.15        163.739907
0.20        154.899191
0.25        144.600000
0.30        136.874066
0.35        125.651503
0.40        112.557725
0.45         96.400000
0.50         85.040447
0.55         73.381138
0.60         63.790725
0.65         48.200000
0.70         48.200000
0.75         45.004863
0.80         39.229348
0.85         34.617098
0.90         30.647120
0.95         26.897955
1.00          0.000000

In [418]:
edc=pd.DataFrame(index=np.arange(0,1.05,0.05))
edc['Energy']=np.percentile(yearly['Energy'],(1-edc.index)*100)

edc

            Energy
0.00  1.005723e+06
0.05  9.445229e+05
0.10  9.212977e+05
0.15  8.965176e+05
0.20  8.793228e+05
0.25  8.650491e+05
0.30  8.578825e+05
0.35  8.487047e+05
0.40  8.445699e+05
0.45  8.387202e+05
0.50  8.314797e+05
0.55  8.272137e+05
0.60  8.242131e+05
0.65  8.139895e+05
0.70  8.027781e+05
0.75  7.915638e+05
0.80  7.839615e+05
0.85  7.644440e+05
0.90  7.562550e+05
0.95  7.154911e+05
1.00  4.873445e+05

In [419]:
yearly['Exceedance']=pd.merge_asof(yearly.reset_index().sort_values('Energy'),edc.reset_index().sort_values('Energy'),left_on='Energy',right_on='Energy').set_index('WaterYear')['index']

## Calendar years
Jan-Dec rather than Oct-Sept

In [420]:
min_year=daily['Year'].min()
max_year=daily['Year'].max()

In [421]:
calyearly=daily.groupby("Year").agg(  
   Energy=('Energy', 'sum'),
).drop([min_year,max_year],axis=0)
calyearly['CapFactor']=calyearly['Energy']/(plant_capacity*24*365)
calyearly.head(5)

             Energy  CapFactor
Year
1925  850283.098736   0.539246
1926  770394.305701   0.488581
1927  852710.195465   0.540785
1928  822963.140104   0.521920
1929  747116.638063   0.473818

## Monthly Day
15th of every month

In [422]:
monthly_day=daily.loc[daily['Day']==15]

## Daily Slim
Slim has less columns and values are rounded so file size is reduced

In [423]:
daily_slim=daily.loc[:,
                     ['Year',
                      'Month',
                      'Day',
                      'WaterYear',
                      'Flow',
                      'EWRRefExceedance',
                      'EWRBandNo',
                      'EWRChannelA',
                      'EWRChannelC',
                      'EWRChannelD',
                      'EWRChannelE',
                      'EWRChannelFG',
                      'EWRTotal',
                      'EWRProportion',
                      'FlowCanal',
                      'FlowSpill',
                      'SpillChannelA',
                      'SpillChannelC',
                      'SpillChannelD',
                      'SpillChannelE',
                      'SpillChannelFG',
                      'FlowChannelA',
                      'FlowChannelC',
                      'FlowChannelD',
                      'FlowChannelE',
                      'FlowChannelFG',
                      'FlowLeftChannel',
                      'FlowTurbine1',
                      'FlowTurbine2',
                      'FlowTurbine3',
                      'FlowTurbine4',
                      'LevelHeadpond',
                      'LevelTailwater',
                      'HeadlossLeftChannel',
                      'HeadlossCanal',
                      'LevelForebay',
                      'Turbines',
                      'HeadTurbine1',
                      'HeadTurbine2',
                      'HeadTurbine3',
                      'HeadTurbine4',
                      'EffTurbine1',
                      'EffTurbine2',
                      'EffTurbine3',
                      'EffTurbine4',
                      'PowerTurbine1',
                      'PowerTurbine2',
                      'PowerTurbine3',
                      'PowerTurbine4',
                      'Power',
                      'Energy'
                     ]
                    ].fillna(0).astype({
                        'Flow': 'int32',
                        'FlowCanal': 'int32',
                        'FlowSpill': 'int32',
                        'EWRChannelA': 'int32',
                        'EWRChannelC': 'int32',
                        'EWRChannelD': 'int32',    
                        'EWRChannelE': 'int32',
                        'EWRChannelFG': 'int32',
                        'EWRTotal': 'int32',    
                        'SpillChannelA': 'int32',
                        'SpillChannelC': 'int32',
                        'SpillChannelD': 'int32',    
                        'SpillChannelE': 'int32',
                        'SpillChannelFG': 'int32',
                        'FlowChannelA': 'int32',
                        'FlowChannelC': 'int32',
                        'FlowChannelD': 'int32',    
                        'FlowChannelE': 'int32',
                        'FlowChannelFG': 'int32',
                        'FlowLeftChannel': 'int32',
                        'FlowTurbine1': 'int32',
                        'FlowTurbine2': 'int32',
                        'FlowTurbine3': 'int32',
                        'FlowTurbine4': 'int32',
                        'Energy': 'int32',
                        
                    }).round({
                            'EWRProportion': 2,
                            'LevelHeadpond': 1,
                            'LevelTailwater': 1,
                            'HeadlossLeftChannel': 2,
                            'HeadlossCanal': 2,
                            'LevelForebay': 1,
                            'PowerTurbine1': 1,
                            'PowerTurbine2': 1,
                            'PowerTurbine3': 1,
                            'PowerTurbine4': 1,
                            'Power': 1,
                            'HeadTurbine1':1,
                            'HeadTurbine2':1,
                            'HeadTurbine3':1,
                            'HeadTurbine4':1,
                            'EffTurbine1':2,
                            'EffTurbine2':2,
                            'EffTurbine3':2,
                            'EffTurbine4':2,    
                    })
daily_slim.tail(12)

,Year,Month,Day,WaterYear,Flow,EWRRefExceedance,EWRBandNo,EWRChannelA,EWRChannelC,EWRChannelD,...,EffTurbine1,EffTurbine2,EffTurbine3,EffTurbine4,PowerTurbine1,PowerTurbine2,PowerTurbine3,PowerTurbine4,Power,Energy
Date,,,,,,,,,,,,,,,,,,,,,
2017-09-19,2017,9,19,2016,216,0.80,4,34,6,4,...,0.91,0.0,0.0,0.0,28.2,0.0,0.0,0.0,27.4,657
2017-09-20,2017,9,20,2016,213,0.80,4,34,6,4,...,0.90,0.0,0.0,0.0,27.5,0.0,0.0,0.0,26.7,639
2017-09-21,2017,9,21,2016,213,0.82,4,34,6,4,...,0.90,0.0,0.0,0.0,27.5,0.0,0.0,0.0,26.7,639
2017-09-22,2017,9,22,2016,209,0.82,4,34,6,4,...,0.90,0.0,0.0,0.0,26.6,0.0,0.0,0.0,25.8,618
2017-09-23,2017,9,23,2016,203,0.82,4,34,6,4,...,0.90,0.0,0.0,0.0,25.0,0.0,0.0,0.0,24.2,581
2017-09-24,2017,9,24,2016,200,0.82,4,34,6,4,...,0.89,0.0,0.0,0.0,24.4,0.0,0.0,0.0,23.6,567
2017-09-25,2017,9,25,2016,200,0.82,4,34,6,4,...,0.89,0.0,0.0,0.0,24.4,0.0,0.0,0.0,23.6,567
2017-09-26,2017,9,26,2016,200,0.82,4,34,6,4,...,0.89,0.0,0.0,0.0,24.4,0.0,0.0,0.0,23.6,567
2017-09-27,2017,9,27,2016,200,0.82,4,34,6,4,...,0.89,0.0,0.0,0.0,24.4,0.0,0.0,0.0,23.6,567
2017-09-28,2017,9,28,2016,200,0.82,4,34,6,4,...,0.89,0.0,0.0,0.0,24.4,0.0,0.0,0.0,23.6,567
2017-09-29,2017,9,29,2016,200,0.82,4,34,6,4,...,0.89,0.0,0.0,0.0,24.4,0.0,0.0,0.0,23.6,567
2017-09-30,2017,9,30,2016,200,0.82,4,34,6,4,...,0.89,0.0,0.0,0.0,24.3,0.0,0.0,0.0,23.5,564

## Weekly & Weekly Slim
Slim has less columns and values are rounded so file size is reduced

In [424]:
weekly=daily.groupby(["WaterYear","WaterWeek"]).mean(numeric_only=True).drop(['Month','WaterMonth','Year','MonthId','Day','WaterDay','EWRBandNo','EWRRefExceedance','Turbines','Energy'],axis=1)

#if 'VicFalls' in weekly.columns:
weekly=weekly.drop(['VicFalls','Conversion','Volume'],axis=1)

weekly=weekly.join(daily.groupby(["WaterYear","WaterWeek"]).agg(    
   Flow_max=('Flow', 'max'),
   Flow_min=('Flow', 'min'), 
   EWRProportion_max=('EWRProportion', 'max'),
   EWRProportion_min=('EWRProportion', 'min'),
   HeadTurbine1_max=('HeadTurbine1', 'max'),
   HeadTurbine1_min=('HeadTurbine1', 'min'),    
   LevelTailwater_max=('LevelTailwater', 'max'),
   LevelTailwater_min=('LevelTailwater', 'min'),  
   Power_max=('Power', 'max'),
   Power_min=('Power', 'min'),    
   Energy=('Energy', 'sum'),
))
weekly=weekly.join(daily[["WaterYear","WaterWeek","Flow"]].groupby(["WaterYear","WaterWeek"]).count().rename(columns={'Flow':'Count'}))
weekly['CapFactor']=weekly['Energy']/(plant_capacity*24*weekly['Count'])
weekly=weekly.join(daily.reset_index('Date')[["WaterYear","WaterWeek","Date"]].groupby(["WaterYear","WaterWeek"]).first().rename(columns={'Date':'StartDate'}))

weekly.tail(12)

                           Flow  Exceedance  Flow_difference  \
WaterYear WaterWeek
2016      42         451.943382    0.593143         6.536288
          43         411.172524    0.638714         4.724796
          44         377.834520    0.678857         5.261728
          45         344.446201    0.716714         4.257422
          46         322.314771    0.751857         2.882230
          47         296.218764    0.791143         3.371720
          48         271.256811    0.834000         3.832214
          49         250.464258    0.873286         3.094980
          50         226.821410    0.915571         2.855981
          51         215.657828    0.933429         1.480060
          52         200.905599    0.953571         1.303758
          53         200.013130    0.958000         0.539477

                     Flow_difference_pct  EWRChannelA  EWRChannelC  \
WaterYear WaterWeek
2016      42                    0.014538    50.000000    10.000000
          43                    0.011456    50.000000    10.000000
          44                    0.013976    43.714286     8.285714
          45                    0.012366    39.000000     7.000000
          46                    0.009020    39.000000     7.000000
          47                    0.011315    39.000000     7.000000
          48                    0.014055    38.285714     6.857143
          49                    0.012470    34.000000     6.000000
          50                    0.012523    34.000000     6.000000
          51                    0.006946    34.000000     6.000000
          52                    0.006443    34.000000     6.000000
          53                    0.002697    34.000000     6.000000

                     EWRChannelD  EWRChannelE  EWRChannelFG    EWRTotal  ...  \
WaterYear WaterWeek                                                      ...
2016      42            9.000000     9.000000    108.000000  186.000000  ...
          43            9.000000     9.000000    108.000000  186.000000  ...
          44            6.714286     6.142857     80.571429  145.428571  ...
          45            5.000000     4.000000     60.000000  115.000000  ...
          46            5.000000     4.000000     60.000000  115.000000  ...
          47            5.000000     4.000000     60.000000  115.000000  ...
          48            4.857143     3.857143     57.714286  111.571429  ...
          49            4.000000     3.000000     44.000000   91.000000  ...
          50            4.000000     3.000000     44.000000   91.000000  ...
          51            4.000000     3.000000     44.000000   91.000000  ...
          52            4.000000     3.000000     44.000000   91.000000  ...
          53            4.000000     3.000000     44.000000   91.000000  ...

                     HeadTurbine1_max  HeadTurbine1_min  LevelTailwater_max  \
WaterYear WaterWeek
2016      42                24.001677         23.730547          965.737526
          43                24.136912         23.904424          965.521550
          44                24.281921         24.050731          965.363713
          45                24.460740         24.268138          965.171201
          46                24.631621         24.479048          965.050892
          47                24.810697         24.686736          964.927004
          48                24.975430         24.844753          964.834273
          49                25.094067         24.944594          964.737471
          50                25.262387         25.139152          964.608432
          51                25.347406         25.262387          964.520236
          52                25.400000         25.400000          964.418141
          53                25.400000         25.400000          964.400079

                     LevelTailwater_min  Power_max  Power_min       Energy  \
WaterYear WaterWeek
2016      42                 965.544031  60.116874  48.200000  8847.499982
          43                 965.394666  48.200000  46.329372  8008.178332
          44                 965.210506  48.200000  42.559931  7773.137656
          45                 965.061496  48.200000  47.981607  8092.358567
          46                 964.960618  47.522141  43.582311  7696.001477
          47                 964.854086  41.995848  37.936486  6684.064376
          48                 964.746784  37.458283  32.474413  5857.952287
          49                 964.640187  36.936944  32.623599  5870.795707
          50                 964.520236  31.447818  28.166185  4986.186332
          51                 964.458073  28.166185  25.790048  4564.910202
          52                 964.403316  24.245032  23.647325  3987.095638
          53                 964.400079  23.512430  23.512430   564.298322

                     Count  CapFactor  StartDate
WaterYear WaterWeek
2016      42             7   0.292576 2017-07-15
          43             7   0.264821 2017-07-22
          44             7   0.257048 2017-07-29
          45             7   0.267604 2017-08-05
          46             7   0.254497 2017-08-12
          47             7   0.221034 2017-08-19
          48             7   0.193715 2017-08-26
          49             7   0.194140 2017-09-02
          50             7   0.164887 2017-09-09
          51             7   0.150956 2017-09-16
          52             7   0.131848 2017-09-23
          53             1   0.130625 2017-09-30

[12 rows x 83 columns]

In [425]:
weekly_slim=weekly.loc[:,
                     [
                      'StartDate',
                      'Flow',
                      'EWRChannelA',
                      'EWRChannelC',
                      'EWRChannelD',
                      'EWRChannelE',
                      'EWRChannelFG',
                      'EWRTotal',
                      'EWRProportion',
                      'FlowCanal',
                      'FlowSpill',
                      'SpillChannelA',
                      'SpillChannelC',
                      'SpillChannelD',
                      'SpillChannelE',
                      'SpillChannelFG',
                      'FlowChannelA',
                      'FlowChannelC',
                      'FlowChannelD',
                      'FlowChannelE',
                      'FlowChannelFG',
                      'FlowLeftChannel',
                      'FlowTurbine1',
                      'FlowTurbine2',
                      'FlowTurbine3',
                      'FlowTurbine4',
                      'LevelHeadpond',
                      'LevelTailwater',
                      'HeadlossLeftChannel',
                      'HeadlossCanal',
                      'LevelForebay',
                      'HeadTurbine1',
                      'HeadTurbine2',
                      'HeadTurbine3',
                      'HeadTurbine4',
                      'EffTurbine1',
                      'EffTurbine2',
                      'EffTurbine3',
                      'EffTurbine4',
                      'PowerTurbine1',
                      'PowerTurbine2',
                      'PowerTurbine3',
                      'PowerTurbine4',
                      'Power',
                      'Energy'
                     ]
                    ].fillna(0).astype({
                        'Flow': 'int32',
                        'FlowCanal': 'int32',
                        'FlowSpill': 'int32',
                        'EWRChannelA': 'int32',
                        'EWRChannelC': 'int32',
                        'EWRChannelD': 'int32',    
                        'EWRChannelE': 'int32',
                        'EWRChannelFG': 'int32',
                        'EWRTotal': 'int32',
                        'SpillChannelA': 'int32',
                        'SpillChannelC': 'int32',
                        'SpillChannelD': 'int32',    
                        'SpillChannelE': 'int32',
                        'SpillChannelFG': 'int32',
                        'FlowChannelA': 'int32',
                        'FlowChannelC': 'int32',
                        'FlowChannelD': 'int32',    
                        'FlowChannelE': 'int32',
                        'FlowChannelFG': 'int32',
                        'FlowLeftChannel': 'int32',
                        'FlowTurbine1': 'int32',
                        'FlowTurbine2': 'int32',
                        'FlowTurbine3': 'int32',
                        'FlowTurbine4': 'int32',
                        'Energy': 'int32',
                        
                    }).round({
                            'EWRProportion':2,
                            'LevelHeadpond': 1,
                            'LevelTailwater': 1,
                            'HeadlossLeftChannel': 2,
                            'HeadlossCanal': 2,
                            'LevelForebay': 1,
                            'PowerTurbine1': 1,
                            'PowerTurbine2': 1,
                            'PowerTurbine3': 1,
                            'PowerTurbine4': 1,
                            'Power': 1,
                            'HeadTurbine1':1,
                            'HeadTurbine2':1,
                            'HeadTurbine3':1,
                            'HeadTurbine4':1,
                            'EffTurbine1':2,
                            'EffTurbine2':2,
                            'EffTurbine3':2,
                            'EffTurbine4':2,
                    })

## Calendar Months

In [426]:
calmonthly=pd.DataFrame({'WaterMonth': [1,2,3,4,5,6,7,8,9,10,11,12],'MonthName': ['Oct','Nov','Dec','Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep'], 'Month':[10,11,12,1,2,3,4,5,6,7,8,9]})
calmonthly=calmonthly.set_index('WaterMonth')
calmonthly=calmonthly.join(monthly.groupby(["WaterMonth"]).agg(    
   EWRProportion_max=('EWRProportion', 'max'),
   EWRProportion_mean=('EWRProportion', 'mean'),
   EWRProportion_median=('EWRProportion', 'median'),
   EWRProportion_min=('EWRProportion', 'min'),
    
    EWRTotal_max=('EWRTotal', 'max'),
   EWRTotal_mean=('EWRTotal', 'mean'),
   EWRTotal_median=('EWRTotal', 'median'),
   EWRTotal_min=('EWRTotal', 'min'),   
    
   FlowCanal_max=('FlowCanal', 'max'),
   FlowCanal_mean=('FlowCanal', 'mean'),
   FlowCanal_median=('FlowCanal', 'median'),
   FlowCanal_min=('FlowCanal', 'min'),     

   FlowSpill_max=('FlowSpill', 'max'),
   FlowSpill_mean=('FlowSpill', 'mean'),
   FlowSpill_median=('FlowSpill', 'median'),
   FlowSpill_min=('FlowSpill', 'min'), 

   HeadTurbine1_max=('HeadTurbine1', 'max'),
   HeadTurbine1_mean=('HeadTurbine1', 'mean'),
   HeadTurbine1_median=('HeadTurbine1', 'median'),
   HeadTurbine1_min=('HeadTurbine1', 'min'), 

   LevelTailwater_max=('LevelTailwater', 'max'),
   LevelTailwater_mean=('LevelTailwater', 'mean'),    
   LevelTailwater_median=('LevelTailwater', 'median'),    
   LevelTailwater_min=('LevelTailwater', 'min'),  
   LevelHeadpond_max=('LevelHeadpond', 'max'),
   LevelHeadpond_mean=('LevelHeadpond', 'mean'),    
   LevelHeadpond_median=('LevelHeadpond', 'median'),    
   LevelHeadpond_min=('LevelHeadpond', 'min'),  
   Turbines_mean=('Turbines', 'mean'),      
   Power_max=('Power', 'max'),
   Power_mean=('Power', 'mean'),
   Power_median=('Power', 'median'),
   Power_min=('Power', 'min'),    
   Energy_max=('Energy', 'max'),
   Energy_mean=('Energy', 'mean'),
   Energy_median=('Energy', 'median'),    
   Energy_min=('Energy', 'min'),
))
calmonthly['Energy_P95']=monthly[['WaterMonth','Energy']].groupby('WaterMonth').quantile(0.05)
calmonthly['Energy_P90']=monthly[['WaterMonth','Energy']].groupby('WaterMonth').quantile(0.10)
calmonthly['Energy_P75']=monthly[['WaterMonth','Energy']].groupby('WaterMonth').quantile(0.25)
calmonthly['Energy_P25']=monthly[['WaterMonth','Energy']].groupby('WaterMonth').quantile(0.75)
calmonthly['Energy_P10']=monthly[['WaterMonth','Energy']].groupby('WaterMonth').quantile(0.90)
calmonthly['Energy_P5']=monthly[['WaterMonth','Energy']].groupby('WaterMonth').quantile(0.95)

calmonthly['Power_P95']=daily[['WaterMonth','Power']].groupby('WaterMonth').quantile(0.05)
calmonthly['Power_P90']=daily[['WaterMonth','Power']].groupby('WaterMonth').quantile(0.10)

calmonthly['FlowAvailableForGeneration_P95']=monthly[['WaterMonth','FlowAvailableForGeneration']].groupby('WaterMonth').quantile(0.05)
calmonthly['FlowAvailableForGeneration_P50']=monthly[['WaterMonth','FlowAvailableForGeneration']].groupby('WaterMonth').quantile(0.5)

# calmonthly['PotentialPower1u_P95']=monthly[['WaterMonth','PotentialPower1u']].groupby('WaterMonth').quantile(0.05)
# calmonthly['PotentialPower1u_P50']=monthly[['WaterMonth','PotentialPower1u']].groupby('WaterMonth').quantile(0.5)
# calmonthly['PotentialPower2u_P95']=monthly[['WaterMonth','PotentialPower2u']].groupby('WaterMonth').quantile(0.05)
# calmonthly['PotentialPower2u_P50']=monthly[['WaterMonth','PotentialPower2u']].groupby('WaterMonth').quantile(0.5)
# calmonthly['PotentialPower3u_P95']=monthly[['WaterMonth','PotentialPower3u']].groupby('WaterMonth').quantile(0.05)
# calmonthly['PotentialPower3u_P50']=monthly[['WaterMonth','PotentialPower3u']].groupby('WaterMonth').quantile(0.5)
# calmonthly['PotentialPower4u_P95']=monthly[['WaterMonth','PotentialPower4u']].groupby('WaterMonth').quantile(0.05)
# calmonthly['PotentialPower4u_P50']=monthly[['WaterMonth','PotentialPower4u']].groupby('WaterMonth').quantile(0.5)


calmonthly['Energy_stdev']=monthly[['WaterMonth','Energy']].groupby('WaterMonth').std()
calmonthly['Energy_coefvar']=calmonthly['Energy_stdev']/calmonthly['Energy_mean']

calmonthly

,MonthName,Month,EWRProportion_max,EWRProportion_mean,EWRProportion_median,EWRProportion_min,EWRTotal_max,EWRTotal_mean,EWRTotal_median,EWRTotal_min,...,Energy_P75,Energy_P25,Energy_P10,Energy_P5,Power_P95,Power_P90,FlowAvailableForGeneration_P95,FlowAvailableForGeneration_P50,Energy_stdev,Energy_coefvar
WaterMonth,,,,,,,,,,,,,,,,,,,,,
1.0,Oct,10,0.578553,0.395209,0.400655,0.274923,120.0,93.278529,97.0,52.0,...,19535.266151,26745.203061,31401.450153,35354.840218,21.019154,22.502917,106.473626,131.828512,6645.056622,0.284205
2.0,Nov,11,0.403429,0.329828,0.333703,0.218705,114.0,88.960573,93.0,50.0,...,23318.387955,31502.329418,38421.937343,43796.312832,24.436940,27.566632,127.246956,170.509616,8310.248086,0.288024
3.0,Dec,12,0.288584,0.240425,0.242757,0.157837,126.0,99.815123,104.0,59.0,...,41305.975694,59800.272007,66783.965003,82119.911810,40.347617,45.198449,224.888099,298.636599,14244.454982,0.279461
4.0,Jan,1,0.222432,0.176738,0.181308,0.097665,150.0,117.388484,120.0,73.0,...,68220.540292,95782.710722,116285.224381,120656.545456,70.049051,74.960543,356.109870,500.581304,20651.755274,0.251441
5.0,Feb,2,0.188832,0.128934,0.138189,0.023961,197.0,138.284920,137.0,85.0,...,88100.403001,110775.063930,119738.843258,122032.844917,94.513457,96.400000,542.376418,850.329902,18207.163715,0.186873
6.0,Mar,3,0.182992,0.094892,0.089986,0.040246,315.0,192.931322,183.0,107.0,...,92736.935382,122039.641063,129995.807620,132929.754440,66.584721,89.558495,743.552377,2138.703847,23699.333459,0.224315
7.0,Apr,4,0.165295,0.084524,0.081270,0.049993,364.0,229.634409,217.0,125.0,...,86882.064581,115338.777957,130371.012005,134613.481279,74.417628,88.255186,955.963161,2724.274054,23209.815072,0.233824
8.0,May,5,0.223150,0.130275,0.127919,0.066393,340.0,264.345473,276.0,147.0,...,106186.388017,127242.984668,131984.598539,134826.953259,105.430432,122.184094,721.570413,1945.779043,16223.158162,0.141705
9.0,Jun,6,0.369425,0.198716,0.193531,0.108731,293.0,211.580645,210.0,119.0,...,94103.097148,121975.243746,124201.746662,125114.201873,63.675305,80.702188,331.378826,968.038152,23778.190747,0.227114
10.0,Jul,7,0.444571,0.334180,0.335820,0.202934,256.0,186.108567,186.0,108.0,...,45777.768750,69117.632852,87664.744208,99747.618593,44.505208,48.200000,219.238140,357.299981,20734.293639,0.350744
11.0,Aug,8,0.470705,0.404513,0.408996,0.303714,202.0,153.313562,155.0,93.0,...,30203.085001,39183.615461,48118.385967,51470.930590,29.602441,33.081659,157.994083,215.139974,9346.998283,0.260145
12.0,Sep,9,0.480201,0.408881,0.414455,0.299250,146.0,116.017921,118.0,72.0,...,22168.270973,29639.290426,35007.254240,38352.144550,23.689408,25.761528,126.437300,158.099494,6651.603877,0.251383

In [427]:
calmonthly[['Power_P90','Power_P95']]

             Power_P90   Power_P95
WaterMonth
1.0          22.502917   21.019154
2.0          27.566632   24.436940
3.0          45.198449   40.347617
4.0          74.960543   70.049051
5.0          96.400000   94.513457
6.0          89.558495   66.584721
7.0          88.255186   74.417628
8.0         122.184094  105.430432
9.0          80.702188   63.675305
10.0         48.200000   44.505208
11.0         33.081659   29.602441
12.0         25.761528   23.689408

In [428]:
calmonthly['PropYearsMinAvailFlowGt1UnitRatedFlow']=monthly[['WaterMonth','FlowAvailableForGeneration_min']].where(lambda x: x['FlowAvailableForGeneration_min']>rated_flow_unit).groupby('WaterMonth').count()/len(yearly.index)
calmonthly['PropYearsMinAvailFlowGt2UnitRatedFlow']=monthly[['WaterMonth','FlowAvailableForGeneration_min']].where(lambda x: x['FlowAvailableForGeneration_min']>rated_flow_unit*2).groupby('WaterMonth').count()/len(yearly.index)
calmonthly['PropYearsMinAvailFlowGt3UnitRatedFlow']=monthly[['WaterMonth','FlowAvailableForGeneration_min']].where(lambda x: x['FlowAvailableForGeneration_min']>rated_flow_unit*3).groupby('WaterMonth').count()/len(yearly.index)
calmonthly['PropYearsMinAvailFlowGtCanalRatedFlow']=monthly[['WaterMonth','FlowAvailableForGeneration_min']].where(lambda x: x['FlowAvailableForGeneration_min']>canal_capacity).groupby('WaterMonth').count()/len(yearly.index)
calmonthly.fillna(0)
calmonthly

,MonthName,Month,EWRProportion_max,EWRProportion_mean,EWRProportion_median,EWRProportion_min,EWRTotal_max,EWRTotal_mean,EWRTotal_median,EWRTotal_min,...,Power_P95,Power_P90,FlowAvailableForGeneration_P95,FlowAvailableForGeneration_P50,Energy_stdev,Energy_coefvar,PropYearsMinAvailFlowGt1UnitRatedFlow,PropYearsMinAvailFlowGt2UnitRatedFlow,PropYearsMinAvailFlowGt3UnitRatedFlow,PropYearsMinAvailFlowGtCanalRatedFlow
WaterMonth,,,,,,,,,,,,,,,,,,,,,
1.0,Oct,10,0.578553,0.395209,0.400655,0.274923,120.0,93.278529,97.0,52.0,...,21.019154,22.502917,106.473626,131.828512,6645.056622,0.284205,0.032258,NaN,NaN,NaN
2.0,Nov,11,0.403429,0.329828,0.333703,0.218705,114.0,88.960573,93.0,50.0,...,24.436940,27.566632,127.246956,170.509616,8310.248086,0.288024,0.053763,NaN,NaN,NaN
3.0,Dec,12,0.288584,0.240425,0.242757,0.157837,126.0,99.815123,104.0,59.0,...,40.347617,45.198449,224.888099,298.636599,14244.454982,0.279461,0.290323,0.021505,NaN,NaN
4.0,Jan,1,0.222432,0.176738,0.181308,0.097665,150.0,117.388484,120.0,73.0,...,70.049051,74.960543,356.109870,500.581304,20651.755274,0.251441,0.967742,0.215054,0.043011,NaN
5.0,Feb,2,0.188832,0.128934,0.138189,0.023961,197.0,138.284920,137.0,85.0,...,94.513457,96.400000,542.376418,850.329902,18207.163715,0.186873,1.000000,0.838710,0.344086,0.129032
6.0,Mar,3,0.182992,0.094892,0.089986,0.040246,315.0,192.931322,183.0,107.0,...,66.584721,89.558495,743.552377,2138.703847,23699.333459,0.224315,1.000000,0.978495,0.795699,0.559140
7.0,Apr,4,0.165295,0.084524,0.081270,0.049993,364.0,229.634409,217.0,125.0,...,74.417628,88.255186,955.963161,2724.274054,23209.815072,0.233824,1.000000,1.000000,0.967742,0.806452
8.0,May,5,0.223150,0.130275,0.127919,0.066393,340.0,264.345473,276.0,147.0,...,105.430432,122.184094,721.570413,1945.779043,16223.158162,0.141705,1.000000,0.946237,0.903226,0.720430
9.0,Jun,6,0.369425,0.198716,0.193531,0.108731,293.0,211.580645,210.0,119.0,...,63.675305,80.702188,331.378826,968.038152,23778.190747,0.227114,0.946237,0.559140,0.258065,0.053763
10.0,Jul,7,0.444571,0.334180,0.335820,0.202934,256.0,186.108567,186.0,108.0,...,44.505208,48.200000,219.238140,357.299981,20734.293639,0.350744,0.473118,0.032258,NaN,NaN
11.0,Aug,8,0.470705,0.404513,0.408996,0.303714,202.0,153.313562,155.0,93.0,...,29.602441,33.081659,157.994083,215.139974,9346.998283,0.260145,0.086022,NaN,NaN,NaN
12.0,Sep,9,0.480201,0.408881,0.414455,0.299250,146.0,116.017921,118.0,72.0,...,23.689408,25.761528,126.437300,158.099494,6651.603877,0.251383,0.021505,NaN,NaN,NaN

In [429]:
# calmonthly['PropYears1uPotentialGtRatedPower']=monthly[['WaterMonth','PotentialPower1u']].where(lambda x: x['PotentialPower1u']>rated_power_unit).groupby('WaterMonth').count()/len(yearly.index)
# calmonthly['PropYears2uPotentialGtRatedPower']=monthly[['WaterMonth','PotentialPower2u']].where(lambda x: x['PotentialPower2u']>rated_power_unit*2).groupby('WaterMonth').count()/len(yearly.index)
# calmonthly['PropYears3uPotentialGtRatedPower']=monthly[['WaterMonth','PotentialPower3u']].where(lambda x: x['PotentialPower3u']>rated_power_unit*3).groupby('WaterMonth').count()/len(yearly.index)
# calmonthly['PropYears4uPotentialGtRatedPower']=monthly[['WaterMonth','PotentialPower4u']].where(lambda x: x['PotentialPower4u']>yearly['Power_max'].max()).groupby('WaterMonth').count()/len(yearly.index)

# calmonthly.fillna(0)
# calmonthly

## Flow duration curve

In [430]:
daily['ExceedanceRnd']=np.round(daily['Exceedance']*2,2)/2
fdc=daily.reset_index().groupby('ExceedanceRnd').mean(numeric_only=True).drop(['VicFalls','Conversion','Year','Month','Day','MonthId','WaterYear','WaterDay','WaterMonth','WaterWeek'],axis=1)
fdc

,Flow,Exceedance,Volume,Flow_difference,Flow_difference_pct,EWRRefExceedance,EWRBandNo,EWRChannelA,EWRChannelC,EWRChannelD,...,EffGen3,EffGen4,PowerGenerator1,PowerGenerator2,PowerGenerator3,PowerGenerator4,Power,Energy,PerfMwPerCumec,PerfMWhPerm3
ExceedanceRnd,,,,,,,,,,,,,,,,,,,,,
0.000,8865.175953,0.001412,0.765951,137.615867,0.015867,0.026324,1.102941,65.735294,12.338235,14.691176,...,0.960000,0.960000,8.970554,8.970554,8.970554,8.970554,35.882217,861.173211,0.004081,inf
0.005,6478.790089,0.004989,0.559767,115.269934,0.017456,0.041149,1.109195,72.281609,13.798851,17.614943,...,0.960000,0.960000,13.920988,13.920988,13.920988,13.920988,55.683952,1336.414854,0.008751,inf
0.010,5544.712707,0.010047,0.479063,68.659047,0.012349,0.077041,1.349112,72.088757,13.514793,17.414201,...,0.960000,0.960000,17.830152,17.830152,17.830152,17.830152,71.320606,1711.694556,0.012882,inf
0.015,5190.964012,0.014953,0.448499,88.798283,0.017178,0.105349,1.447674,70.889535,12.941860,16.552326,...,0.961831,0.961831,19.755422,19.755422,19.755422,19.755422,79.021689,1896.520547,0.015239,0.000020
0.020,4777.593171,0.020076,0.412784,113.350030,0.023656,0.110465,1.430233,69.651163,13.156977,16.569767,...,0.967428,0.967428,22.552382,22.552382,22.552382,22.552382,90.209528,2165.028682,0.018915,0.000023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0.980,185.643897,0.979851,0.016040,2.397496,0.012948,0.897619,4.541667,27.809524,4.333333,2.678571,...,0.960000,0.960000,26.449377,0.000000,0.000000,0.000000,26.449377,634.785048,0.142442,0.000060
0.985,175.260665,0.985178,0.015143,1.918049,0.010903,0.920385,4.774038,26.028846,4.254808,2.432692,...,0.960000,0.960000,25.262322,0.000000,0.000000,0.000000,25.262322,606.295730,0.144221,0.000060
0.990,165.025295,0.990459,0.014258,2.091723,0.012641,0.944222,4.970370,24.659259,4.251852,2.281481,...,0.960000,0.960000,23.808784,0.000000,0.000000,0.000000,23.808784,571.410812,0.144248,0.000060
0.995,148.857160,0.995030,0.012861,2.587904,0.017189,0.976131,5.000000,25.047619,4.488095,2.488095,...,0.960000,0.960000,19.479009,0.000000,0.000000,0.000000,19.479009,467.496213,0.130399,0.000058
1.000,117.318495,0.998830,0.010136,1.280625,0.015760,0.942500,4.800000,25.180000,4.100000,2.100000,...,0.960000,0.960000,11.696369,0.000000,0.000000,0.000000,11.696369,280.712851,0.098646,0.000054

## Add overall summary data to the model file

In [431]:
autocorrel=pd.DataFrame(statools.acf(yearly['Energy'],fft=True,qstat=False,alpha=0.05))
autocorrel

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,1.0,0.544937,0.39782,0.311661,0.294007,0.195123,0.165653,0.152728,0.20911,0.118031,0.081023,-0.010089,-0.085688,-0.062333,-0.162622,-0.196064,-0.197693,-0.255328,-0.273142,-0.230564
1,"[1.0, 1.0]","[0.34169803326250425, 0.7481756283383855]","[0.14123099510840198, 0.6544099326864427]","[0.03074739081189576, 0.5925745032072538]","[-0.0008432059053292695, 0.5888575373571867]","[-0.11159800104523063, 0.5018439019715623]","[-0.14615298434134105, 0.4774591599170519]","[-0.16269190787756807, 0.46814873282362723]","[-0.1093501724452001, 0.5275704937864389]","[-0.20605165988255036, 0.4421130240135349]","[-0.24482974876296335, 0.4068764806532629]","[-0.33677336948210046, 0.3165950796115329]","[-0.4123846523096597, 0.2410095371805193]","[-0.38995718292123493, 0.2652910408353081]","[-0.49073558631007186, 0.1654916316190003]","[-0.527490619600611, 0.1353616721391947]","[-0.5338760830997932, 0.13848989370496345]","[-0.5962792522157534, 0.08562305985579582]","[-0.6219016192264664, 0.07561789887550985]","[-0.5880511366864488, 0.1269223202396257]"

In [432]:
lowheadshutdowns=daily.loc[daily['LowHeadShutoff']==1].groupby('WaterYear').count()['Flow'].to_frame().rename(columns={"Flow":"Days"})

lowheadshutdowns['StartDate']=daily[['WaterYear','Flow']].loc[daily['LowHeadShutoff']==1].reset_index().groupby('WaterYear').min()['Date']
lowheadshutdowns['EndDate']=daily[['WaterYear','Flow']].loc[daily['LowHeadShutoff']==1].reset_index().groupby('WaterYear').max()['Date']
lowheadshutdowns['MonthId']=daily[['WaterYear','MonthId']].loc[daily['LowHeadShutoff']==1].reset_index().groupby('WaterYear').min()['MonthId']

#daily.loc[daily['LowHeadShutoff']==1].groupby('WaterYear').min()#['Date']
lowheadshutdowns['Month_power_max']=monthly.loc[lowheadshutdowns['MonthId']][['WaterYear','Power_max']].set_index('WaterYear')
lowheadshutdowns

           Days  StartDate    EndDate  MonthId  Month_power_max
WaterYear
1933          6 1934-03-24 1934-03-29  1934.03       182.902490
1947         34 1948-03-04 1948-04-06  1948.03       102.106098
1951         20 1952-03-02 1952-03-21  1952.03       100.175652
1952         11 1953-03-21 1953-03-31  1953.03       189.612525
1955         16 1956-05-03 1956-05-18  1956.05       113.706108
1956         27 1957-03-02 1957-03-28  1957.03       101.672851
1957         61 1958-02-03 1958-04-04  1958.02       108.463141
1960         24 1961-04-01 1961-04-24  1961.04        93.102924
1961         15 1962-04-03 1962-04-17  1962.04        98.938010
1962         47 1963-03-02 1963-04-17  1963.03        76.351293
1965          2 1966-04-01 1966-04-02  1966.04       139.197658
1967          7 1968-04-02 1968-04-10  1968.04       125.655145
1968         60 1969-03-02 1969-04-30  1969.03        83.235858
1974          7 1975-04-01 1975-04-07  1975.04       117.291561
1975          3 1976-03-31 1976-04-02  1976.03       188.600730
1977         37 1978-03-31 1978-05-06  1978.03       163.034304
2008         20 2009-03-16 2009-04-04  2009.03       150.120765

In [433]:
lowflowshutdowns=daily.loc[daily['LowFlowShutoff']==1].groupby('Year').count()['Flow'].to_frame().rename(columns={"Flow":"Days"})

lowflowshutdowns['StartDate']=daily[['Year','Flow']].loc[daily['LowFlowShutoff']==1].reset_index().groupby('Year').min()['Date']
lowflowshutdowns['EndDate']=daily[['Year','Flow']].loc[daily['LowFlowShutoff']==1].reset_index().groupby('Year').max()['Date']
lowflowshutdowns['MonthId']=daily[['Year','MonthId']].loc[daily['LowFlowShutoff']==1].reset_index().groupby('Year').min()['MonthId']


lowflowshutdowns['Month_power_max']=monthly.loc[lowflowshutdowns['MonthId']][['Year','Power_max']].set_index('Year')
lowflowshutdowns

      Days  StartDate    EndDate  MonthId  Month_power_max
Year
1924    10 1924-10-01 1924-10-10   1924.1        15.061287

In [434]:

models.at[model_name,'Mean']=yearly['Energy'].mean()
models.at[model_name,'Max']=yearly['Energy'].max()
models.at[model_name,'Min']=yearly['Energy'].min()

models.at[model_name,'P95']=yearly['Energy'].quantile(0.05)
models.at[model_name,'P90']=yearly['Energy'].quantile(0.10)
models.at[model_name,'P75']=yearly['Energy'].quantile(0.25)
models.at[model_name,'P50']=yearly['Energy'].quantile(0.5)
models.at[model_name,'P25']=yearly['Energy'].quantile(0.75)
models.at[model_name,'P10']=yearly['Energy'].quantile(0.90)
models.at[model_name,'P5']=yearly['Energy'].quantile(0.95)

models.at[model_name,'StDev']=yearly['Energy'].std()
models.at[model_name,'CoefVar']=models.at[model_name,'StDev']/models.at[model_name,'Mean']

models.at[model_name,'CapFactor']=yearly['CapFactor'].mean()

models.at[model_name,'CalYearMean']=calyearly['Energy'].mean()
models.at[model_name,'CalYearStDev']=calyearly['Energy'].std()
models.at[model_name,'CalYearCoefVar']=models.at[model_name,'CalYearStDev']/models.at[model_name,'CalYearMean']

models.at[model_name,'Power_max']=yearly['Power_max'].max()
models.at[model_name,'Power_Turbine1_max']=yearly['PowerTurbine1_max'].max()

models.at[model_name,'CapFactor_Power_max']=calyearly['Energy'].mean()/(yearly['Power_max'].max()*24*365)

#models.at[model_name,'RatedPower']=rated_power_unit

models.at[model_name,'P95FirmPower']=power_exceed.iloc[19]
models.at[model_name,'P90FirmPower']=power_exceed.iloc[18]

models.loc[model_name]

C:\Users\Andy Fleming\AppData\Local\Temp\ipykernel_10404\3622041741.py:29: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  models.at[model_name,'P95FirmPower']=power_exceed.iloc[19]
C:\Users\Andy Fleming\AppData\Local\Temp\ipykernel_10404\3622041741.py:30: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  models.at[model_name,'P90FirmPower']=power_exceed.iloc[18]

OutputPrefix                                               base_tender
Description             Base Case as provided to EPC Tender candidates
EWRCatSet                                             Recommendation 1
TailwaterLift                                                      0.0
HeadpondLift                                                       0.0
Capacity                                                           180
MinimumHead                                                       10.0
MaximumHead                                                       25.4
MaxHeadShutdown                                                    0.0
MinimumFlowUnit                                                   50.0
MaximumFlowUnit                                                  275.0
UnitsAvailable                                                       4
RatedDischarge                                                   250.0
RatedTurbineCapacity                                              49.1
MaxGeneratorOutput                                                48.2
OptimiseTurbines                                                     0
SinoHillchart                                                        0
SinoHeadlosses                                                       0
Mean                                                     828370.524152
P95                                                      715491.078684
P90                                                      756255.037323
P75                                                      791563.774163
P50                                                      831479.739441
P25                                                      865049.148011
P10                                                      921297.666883
P5                                                       944522.904684
StDev                                                     80703.703173
CoefVar                                                       0.097425
Max                                                     1005722.657187
Min                                                      487344.503302
CapFactor                                                     0.525349
CalYearMean                                              828469.058294
CalYearStDev                                              78872.987434
CalYearCoefVar                                                0.095203
AutoCorrel                                                         NaN
Power_max                                                        192.8
CapFactor_Power_max                                            0.49053
Power_Turbine1_max                                           61.532301
P95FirmPower                                                 26.897955
P90FirmPower                                                  30.64712
Name: Base Case Tender, dtype: object

## Save Files

In [435]:
outp=output_data+out_prefix

if dryrun==False:
    daily.to_csv(outp+'_pe_daily.csv')
    monthly.to_csv(outp+'_pe_monthly.csv')
    yearly.to_csv(outp+'_pe_yearly.csv')
    edc.to_csv(outp+'_pe_percentiles.csv')
    monthly_day.to_csv(outp+'_pe_monthly_day.csv')
    daily_slim.to_csv(outp+'_pe_daily_slim.csv')
    weekly.to_csv(outp+'_pe_weekly.csv')
    weekly_slim.to_csv(outp+'_pe_weekly_slim.csv')
    calmonthly.to_csv(outp+'_pe_calmonthly.csv')
    power_exceed.to_csv(outp+'_pe_power_exceed.csv')
    fdc.to_csv(outp+'_pe_fdc.csv')
    autocorrel.to_csv(outp+'_pe_autocorrel.csv')
    lowheadshutdowns.to_csv(outp + "lowheadshutdowns.csv")
    lowflowshutdowns.to_csv(outp + "lowflowshutdowns.csv")

    if year != '':
        models.to_csv(input_data + year + "/models.csv")
    else:
        models.to_csv(input_data + "models.csv")

In [437]:
if output_separate_years:
    years=daily['WaterYear'].unique().tolist()
    for year in years:
        days=daily.loc[daily.WaterYear==year]
        days.to_csv(output_data + 'years/' + out_prefix + '_pe_daily_' + str(year) + '.csv')